name: authenticator_storage
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  authenticator:
    git:
      url: https://github.com/daniellampl/authenticator.git
      path: packages/authenticator
  flutter_secure_storage: ^8.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  deckweiss_lints: ^2.0.1
