name: authenticator_storage
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  authenticator:
    path: ../authenticator
  flutter_secure_storage: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  deckweiss_lints: ^1.0.0+1
