name: oidc_authenticator_web
description: A new Flutter plugin project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  http: ^1.2.0

  oidc_authenticator_platform_interface:
    git:
      url: https://github.com/daniellampl/authenticator.git
      path: packages/oidc_authenticator/oidc_authenticator_platform_interface
      ref: web-support
  oidc_client:
    git:
      url: https://github.com/daniellampl/authenticator.git
      path: packages/oidc_authenticator/oidc_client
      ref: web-support

dev_dependencies:
  deckweiss_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      web:
        pluginClass: OidcAuthenticatorWeb
        fileName: oidc_authenticator_web.dart
