name: oidc_client
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^1.2.0
  pointycastle: ^3.7.4

dev_dependencies:
  build_runner: ^2.4.8
  deckweiss_lints: ^2.0.1
